import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Calendar, Users, Trophy, BookOpen, ArrowRight, Star, Zap, Award, HelpCircle, LifeBuoy, CheckCircle } from 'lucide-react';
import { Tenant, Tournament, Plan, storage, STORAGE_KEYS, mockTournaments, defaultPlans } from '@/lib/mockData';
import { Dialog, DialogContent } from '@/components/ui/dialog';
import { AuthSystem } from '@/components/AuthSystem';
import { TenantAvatar } from '@/components/TenantAvatar';

// Local currency formatter
const formatCurrency = (amount: number, currency: string = 'USD', locale: string = 'en-US'): string => {
  return new Intl.NumberFormat(locale, {
    style: 'currency',
    currency: currency,
  }).format(amount);
};

interface TenantLandingContent {
  hero: {
    headline: string;
    subheadline: string;
    ctaText: string;
    ctaSecondaryText: string;
  };
  stats: {
    questionsCount: string;
    activeTournaments: string;
    practiceAccess: string;
  };
  features: Array<{
    id: string;
    icon: string;
    title: string;
    description: string;
    enabled: boolean;
  }>;
  branding: {
    showOrgLogo: boolean;
    showPoweredBy: boolean;
    customFooterText?: string;
  };
}

const defaultLandingContent = (tenantName: string): TenantLandingContent => ({
  hero: {
    headline: `Join ${tenantName}'s Bible Quiz Community`,
    subheadline: 'Test your knowledge, compete with others, and grow in your faith.',
    ctaText: 'Get Started',
    ctaSecondaryText: 'I Already Have an Account'
  },
  stats: {
    questionsCount: '5,000+',
    activeTournaments: '1',
    practiceAccess: '24/7'
  },
  features: [
    {
      id: 'tournaments',
      icon: 'trophy',
      title: 'Competitive Tournaments',
      description: 'Join live tournaments and compete with fellow Bible scholars',
      enabled: true
    },
    {
      id: 'practice',
      icon: 'book-open',
      title: 'Practice Mode',
      description: 'Sharpen your skills with unlimited practice questions',
      enabled: true
    },
    {
      id: 'leaderboard',
      icon: 'users',
      title: 'Global Leaderboard',
      description: 'Track your progress and see how you rank',
      enabled: true
    },
    {
      id: 'ai-powered',
      icon: 'star',
      title: 'AI-Powered Questions',
      description: 'Challenging questions generated by advanced AI',
      enabled: true
    }
  ],
  branding: {
    showOrgLogo: true,
    showPoweredBy: true,
    customFooterText: ''
  }
});

interface TenantLandingPageProps {
  tenant: Tenant;
  onAuthSuccess: () => void;
}

export const TenantLandingPage: React.FC<TenantLandingPageProps> = ({ tenant, onAuthSuccess }) => {
  const [showAuthModal, setShowAuthModal] = useState(false);
  const [showHelpModal, setShowHelpModal] = useState(false);
  const [featuredTournament, setFeaturedTournament] = useState<Tournament | null>(null);
  const [tournamentType, setTournamentType] = useState<'upcoming' | 'past' | null>(null);
  const [plan, setPlan] = useState<Plan | null>(null);
  const [landingContent, setLandingContent] = useState<TenantLandingContent>(defaultLandingContent(tenant.name));

  useEffect(() => {
    // Load custom landing page content from storage
    try {
      const storageKey = `tenant_landing_${tenant.id}`;
      const savedContent = storage.get(storageKey);
      
      if (savedContent) {
        setLandingContent(savedContent);
      } else {
        setLandingContent(defaultLandingContent(tenant.name));
      }
    } catch (error) {
      console.error('Failed to load landing page content:', error);
      setLandingContent(defaultLandingContent(tenant.name));
    }
  }, [tenant.id, tenant.name]);

  useEffect(() => {
    // Load tournaments for this tenant
    const tournaments = storage.get(STORAGE_KEYS.TOURNAMENTS) || mockTournaments;
    const tenantTournaments = tournaments.filter((t: Tournament) => t.tenantId === tenant.id);
    
    // Priority 1: Show upcoming/active tournament
    const upcomingTournament = tenantTournaments
      .filter((t: Tournament) => t.status === 'scheduled' || t.status === 'active')
      .sort((a: Tournament, b: Tournament) => new Date(a.startDate).getTime() - new Date(b.startDate).getTime())[0];
    
    if (upcomingTournament) {
      setFeaturedTournament(upcomingTournament);
      setTournamentType('upcoming');
    } else {
      // Priority 2: Show most recent past tournament
      const pastTournament = tenantTournaments
        .filter((t: Tournament) => t.status === 'completed')
        .sort((a: Tournament, b: Tournament) => new Date(b.endDate).getTime() - new Date(a.endDate).getTime())[0];
      
      if (pastTournament) {
        setFeaturedTournament(pastTournament);
        setTournamentType('past');
      } else {
        setFeaturedTournament(null);
        setTournamentType(null);
      }
    }

    // Load tenant's plan for white-label check
    const plans = storage.get(STORAGE_KEYS.PLANS) || defaultPlans;
    const tenantPlan = plans.find((p: Plan) => p.id === tenant.planId);
    setPlan(tenantPlan || null);
  }, [tenant.id, tenant.planId]);

  const handleCTAClick = () => {
    setShowAuthModal(true);
  };

  const formatDate = (dateString: string) => {
    try {
      return new Date(dateString).toLocaleDateString('en-US', { 
        month: 'short', 
        day: 'numeric', 
        year: 'numeric' 
      });
    } catch {
      return dateString;
    }
  };

  const getTournamentStatus = (tournament: Tournament) => {
    const now = new Date();
    const startDate = new Date(tournament.startDate);
    
    if (tournament.status === 'active') {
      return { label: 'Active Now', color: 'bg-green-500' };
    } else if (tournament.status === 'scheduled') {
      const daysUntil = Math.ceil((startDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
      if (daysUntil <= 7) {
        return { label: `${daysUntil} days left`, color: 'bg-orange-500' };
      }
      return { label: 'Upcoming', color: 'bg-blue-500' };
    }
    return { label: 'Active', color: 'bg-purple-500' };
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 sticky top-0 z-40 backdrop-blur-sm bg-white/95">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <TenantAvatar tenant={tenant} size="md" showName={true} />
          
          <div className="flex items-center gap-3">
            {/* Platform Status Indicator */}
            <Badge variant="outline" className="flex items-center gap-1.5 bg-green-50 text-green-700 border-green-200">
              <CheckCircle className="h-3 w-3" />
              <span className="text-xs">All Systems Operational</span>
            </Badge>
            
            {/* Help & Support */}
            <Button variant="ghost" size="sm" onClick={() => setShowHelpModal(true)}>
              <HelpCircle className="h-4 w-4 mr-1" />
              Help
            </Button>
            
            <Button variant="ghost" onClick={() => handleCTAClick()}>
              Login
            </Button>
            <Button 
              onClick={() => handleCTAClick()}
              style={{ backgroundColor: tenant.primaryColor || '#2563eb' }}
              className="text-white hover:opacity-90"
            >
              Join Now
            </Button>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative py-20 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-600/10 via-purple-600/10 to-pink-600/10" />
        <div className="container mx-auto px-4 relative z-10">
          <div className="max-w-4xl mx-auto text-center">
            <Badge className="mb-4 px-4 py-1.5 text-sm" variant="secondary">
              <Zap className="w-4 h-4 mr-1 inline" />
              Live Bible Quiz Platform
            </Badge>
            <h2 className="text-5xl md:text-6xl font-bold mb-6 bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
              {landingContent.hero.headline}
            </h2>
            <p className="text-xl md:text-2xl text-gray-600 mb-8 max-w-2xl mx-auto">
              {landingContent.hero.subheadline}
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
              <Button 
                size="lg" 
                onClick={() => handleCTAClick()}
                style={{ backgroundColor: tenant.primaryColor || '#2563eb' }}
                className="text-white px-8 py-6 text-lg hover:opacity-90"
              >
                {landingContent.hero.ctaText}
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
              <Button 
                size="lg" 
                variant="outline" 
                onClick={() => handleCTAClick()}
                className="px-8 py-6 text-lg"
              >
                {landingContent.hero.ctaSecondaryText}
              </Button>
            </div>
            
            {/* Quick Stats */}
            <div className="grid grid-cols-3 gap-6 mt-12 max-w-2xl mx-auto">
              <div className="text-center">
                <div className="text-3xl font-bold text-blue-600">{landingContent.stats.questionsCount}</div>
                <div className="text-sm text-gray-600">Questions</div>
              </div>
              <div className="text-center">
                <div className="text-3xl font-bold text-purple-600">{landingContent.stats.activeTournaments}</div>
                <div className="text-sm text-gray-600">Active Tournaments</div>
              </div>
              <div className="text-center">
                <div className="text-3xl font-bold text-pink-600">{landingContent.stats.practiceAccess}</div>
                <div className="text-sm text-gray-600">Practice Access</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Featured Tournament Section */}
      {featuredTournament && (
        <section className="py-16 bg-white">
          <div className="container mx-auto px-4">
            <div className="max-w-5xl mx-auto">
              <div className="text-center mb-8">
                <h3 className="text-3xl font-bold mb-3">
                  {tournamentType === 'upcoming' ? 'Featured Tournament' : 'Recent Tournament'}
                </h3>
                <p className="text-gray-600 text-lg">
                  {tournamentType === 'upcoming' 
                    ? 'Register now and compete with fellow Bible scholars' 
                    : 'See the results from our latest competition'}
                </p>
              </div>

              <Card className="overflow-hidden border-2 border-gray-200 shadow-xl">
                <div className="bg-gradient-to-r from-blue-600 to-purple-600 p-8 text-white">
                  <div className="flex items-start justify-between mb-4">
                    <div className="flex items-center gap-3">
                      <Trophy className="h-12 w-12" />
                      <div>
                        <h4 className="text-3xl font-bold">{featuredTournament.name}</h4>
                        <p className="text-blue-100 text-lg mt-1">
                          {featuredTournament.description || 'Test your Bible knowledge and compete for prizes'}
                        </p>
                      </div>
                    </div>
                    <Badge 
                      className={`${tournamentType === 'upcoming' ? getTournamentStatus(featuredTournament).color : 'bg-gray-500'} text-white text-sm px-4 py-2`}
                    >
                      {tournamentType === 'upcoming' 
                        ? getTournamentStatus(featuredTournament).label 
                        : 'Completed'}
                    </Badge>
                  </div>
                </div>

                <CardContent className="p-8">
                  <div className="grid md:grid-cols-3 gap-8 mb-8">
                    {/* Date */}
                    <div className="text-center md:text-left">
                      <div className="flex items-center justify-center md:justify-start text-gray-500 mb-2">
                        <Calendar className="h-5 w-5 mr-2" />
                        <span className="text-sm font-medium uppercase tracking-wide">
                          {tournamentType === 'upcoming' ? 'Start Date' : 'Completed'}
                        </span>
                      </div>
                      <div className="text-2xl font-bold text-gray-900">
                        {formatDate(tournamentType === 'upcoming' ? featuredTournament.startDate : featuredTournament.endDate)}
                      </div>
                      {tournamentType === 'upcoming' && (() => {
                        const now = new Date();
                        const startDate = new Date(featuredTournament.startDate);
                        const daysUntil = Math.ceil((startDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
                        return (
                          <div className="text-sm text-gray-600 mt-1">
                            {daysUntil > 0 ? `${daysUntil} days to go` : 'Starting soon!'}
                          </div>
                        );
                      })()}
                    </div>

                    {/* Participants */}
                    {featuredTournament.maxParticipants && (
                      <div className="text-center md:text-left">
                        <div className="flex items-center justify-center md:justify-start text-gray-500 mb-2">
                          <Users className="h-5 w-5 mr-2" />
                          <span className="text-sm font-medium uppercase tracking-wide">Participants</span>
                        </div>
                        <div className="text-2xl font-bold text-gray-900">
                          {tournamentType === 'upcoming' ? '45' : featuredTournament.maxParticipants} / {featuredTournament.maxParticipants}
                        </div>
                        {tournamentType === 'upcoming' && (
                          <>
                            <div className="text-sm text-gray-600 mt-1">
                              {featuredTournament.maxParticipants - 45} spots remaining
                            </div>
                            <div className="mt-3 bg-gray-200 rounded-full h-2 overflow-hidden">
                              <div 
                                className="bg-gradient-to-r from-green-500 to-blue-500 h-full transition-all duration-500"
                                style={{ width: `${(45 / featuredTournament.maxParticipants) * 100}%` }}
                              />
                            </div>
                          </>
                        )}
                      </div>
                    )}

                    {/* Entry Fee */}
                    <div className="text-center md:text-left">
                      <div className="flex items-center justify-center md:justify-start text-gray-500 mb-2">
                        <Award className="h-5 w-5 mr-2" />
                        <span className="text-sm font-medium uppercase tracking-wide">
                          {tournamentType === 'upcoming' ? 'Entry Fee' : 'Prize Pool'}
                        </span>
                      </div>
                      <div className="text-2xl font-bold text-gray-900">
                        {featuredTournament.entryFee > 0 
                          ? formatCurrency(featuredTournament.entryFee)
                          : 'FREE'}
                      </div>
                    </div>
                  </div>

                  {/* CTA Buttons */}
                  <div className="flex flex-col sm:flex-row gap-4 pt-6 border-t border-gray-200">
                    {tournamentType === 'upcoming' ? (
                      <>
                        <Button 
                          size="lg"
                          className="flex-1 text-lg py-6"
                          onClick={() => handleCTAClick()}
                          style={{ backgroundColor: tenant.primaryColor || '#2563eb' }}
                        >
                          <Trophy className="mr-2 h-5 w-5" />
                          Register for Tournament
                        </Button>
                        <Button 
                          size="lg"
                          variant="outline"
                          className="flex-1 text-lg py-6"
                          onClick={() => handleCTAClick()}
                        >
                          View Details
                          <ArrowRight className="ml-2 h-5 w-5" />
                        </Button>
                      </>
                    ) : (
                      <>
                        <Button 
                          size="lg"
                          variant="outline"
                          className="flex-1 text-lg py-6"
                          onClick={() => handleCTAClick()}
                        >
                          <Trophy className="mr-2 h-5 w-5" />
                          View Results
                        </Button>
                        <Button 
                          size="lg"
                          className="flex-1 text-lg py-6"
                          onClick={() => handleCTAClick()}
                          style={{ backgroundColor: tenant.primaryColor || '#2563eb' }}
                        >
                          Join Next Tournament
                          <ArrowRight className="ml-2 h-5 w-5" />
                        </Button>
                      </>
                    )}
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      )}

      {/* Practice Mode Section */}
      <section className="py-16 bg-gradient-to-br from-purple-50 to-blue-50">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <div className="text-center mb-12">
              <BookOpen className="h-16 w-16 mx-auto mb-4 text-purple-600" />
              <h3 className="text-3xl font-bold mb-3">Practice Anytime, Anywhere</h3>
              <p className="text-gray-600 text-lg">
                Sharpen your Bible knowledge with unlimited practice sessions
              </p>
            </div>
            
            <div className="grid md:grid-cols-3 gap-6 mb-8">
              <Card className="text-center">
                <CardHeader>
                  <div className="mx-auto mb-3 h-12 w-12 rounded-full bg-blue-100 flex items-center justify-center">
                    <BookOpen className="h-6 w-6 text-blue-600" />
                  </div>
                  <CardTitle className="text-lg">5,000+ Questions</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-gray-600">
                    Comprehensive question bank covering Old and New Testament
                  </p>
                </CardContent>
              </Card>
              
              <Card className="text-center">
                <CardHeader>
                  <div className="mx-auto mb-3 h-12 w-12 rounded-full bg-purple-100 flex items-center justify-center">
                    <Zap className="h-6 w-6 text-purple-600" />
                  </div>
                  <CardTitle className="text-lg">Instant Feedback</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-gray-600">
                    Get immediate explanations and track your progress
                  </p>
                </CardContent>
              </Card>
              
              <Card className="text-center">
                <CardHeader>
                  <div className="mx-auto mb-3 h-12 w-12 rounded-full bg-pink-100 flex items-center justify-center">
                    <Star className="h-6 w-6 text-pink-600" />
                  </div>
                  <CardTitle className="text-lg">Level Up</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-gray-600">
                    Earn XP, unlock achievements, and climb the leaderboard
                  </p>
                </CardContent>
              </Card>
            </div>
            
            <div className="text-center">
              <Button 
                size="lg"
                onClick={() => handleCTAClick()}
                style={{ backgroundColor: tenant.primaryColor || '#2563eb' }}
                className="text-white px-8 py-6 text-lg"
              >
                Start Practicing Now
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-16 bg-white">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h3 className="text-3xl font-bold mb-3">How It Works</h3>
            <p className="text-gray-600 text-lg">Get started in just a few simple steps</p>
          </div>
          
          <div className="max-w-4xl mx-auto">
            <div className="grid md:grid-cols-4 gap-8">
              {['Sign Up', 'Choose Your Parish', 'Practice & Learn', 'Compete & Win'].map((step, index) => (
                <div key={index} className="text-center">
                  <div 
                    className="w-16 h-16 rounded-full mx-auto mb-4 flex items-center justify-center text-white text-2xl font-bold"
                    style={{ backgroundColor: tenant.primaryColor || '#2563eb' }}
                  >
                    {index + 1}
                  </div>
                  <h4 className="font-semibold mb-2">{step}</h4>
                  <p className="text-sm text-gray-600">
                    {index === 0 && 'Create your free account in seconds'}
                    {index === 1 && 'Join your church community'}
                    {index === 2 && 'Build your Bible knowledge daily'}
                    {index === 3 && 'Join tournaments and earn prizes'}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20 bg-gradient-to-br from-blue-600 to-purple-600 text-white">
        <div className="container mx-auto px-4 text-center">
          <h3 className="text-4xl font-bold mb-4">Ready to Begin Your Journey?</h3>
          <p className="text-xl mb-8 text-blue-100 max-w-2xl mx-auto">
            Join hundreds of Bible quizzers improving their knowledge and competing for glory
          </p>
          <Button 
            size="lg"
            onClick={() => handleCTAClick()}
            className="bg-white text-blue-600 hover:bg-blue-50 px-8 py-6 text-lg"
          >
            Join {tenant.name} Today
            <ArrowRight className="ml-2 h-5 w-5" />
          </Button>
          <p className="mt-4 text-sm text-blue-200">
            Free to join • No credit card required • Start practicing immediately
          </p>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-300 py-12">
        <div className="container mx-auto px-4">
          <div className="grid md:grid-cols-4 gap-8 mb-8">
            {/* About Section */}
            <div>
              <h4 className="text-white font-semibold mb-4">About {tenant.name}</h4>
              <p className="text-sm text-gray-400">
                Join our Bible quiz community and test your knowledge while growing in faith.
              </p>
            </div>
            
            {/* Quick Links */}
            <div>
              <h4 className="text-white font-semibold mb-4">Quick Links</h4>
              <ul className="space-y-2 text-sm">
                <li>
                  <button onClick={() => handleCTAClick()} className="text-gray-400 hover:text-white transition-colors">
                    Tournaments
                  </button>
                </li>
                <li>
                  <button onClick={() => handleCTAClick()} className="text-gray-400 hover:text-white transition-colors">
                    Practice Mode
                  </button>
                </li>
                <li>
                  <button onClick={() => handleCTAClick()} className="text-gray-400 hover:text-white transition-colors">
                    Leaderboard
                  </button>
                </li>
              </ul>
            </div>
            
            {/* Support */}
            <div>
              <h4 className="text-white font-semibold mb-4">Support</h4>
              <ul className="space-y-2 text-sm">
                <li>
                  <button onClick={() => setShowHelpModal(true)} className="text-gray-400 hover:text-white transition-colors flex items-center gap-2">
                    <HelpCircle className="h-4 w-4" />
                    Help Center
                  </button>
                </li>
                <li>
                  <button onClick={() => handleCTAClick()} className="text-gray-400 hover:text-white transition-colors flex items-center gap-2">
                    <LifeBuoy className="h-4 w-4" />
                    Contact Support
                  </button>
                </li>
                <li>
                  <a href="http://localhost:3000" className="text-gray-400 hover:text-white transition-colors">
                    Platform Status
                  </a>
                </li>
              </ul>
            </div>
            
            {/* Legal */}
            <div>
              <h4 className="text-white font-semibold mb-4">Legal</h4>
              <ul className="space-y-2 text-sm">
                <li>
                  <a href="http://localhost:3000/terms" className="text-gray-400 hover:text-white transition-colors">
                    Terms of Service
                  </a>
                </li>
                <li>
                  <a href="http://localhost:3000/privacy" className="text-gray-400 hover:text-white transition-colors">
                    Privacy Policy
                  </a>
                </li>
              </ul>
            </div>
          </div>
          
          {/* Copyright */}
          <div className="border-t border-gray-800 pt-8 text-center">
            {plan?.features?.some(f => f.includes('White-label') || f.includes('Full custom branding') || f.includes('Custom branding')) ? (
              <p className="text-sm">
                © {new Date().getFullYear()} {tenant.name}. All rights reserved.
              </p>
            ) : (
              <p className="text-sm">
                © {new Date().getFullYear()} Smart eQuiz Platform. All rights reserved.
                <br />
                <span className="text-gray-500 text-xs mt-1 inline-block">Powering {tenant.name}</span>
              </p>
            )}
          </div>
        </div>
      </footer>

      {/* Help Modal */}
      <Dialog open={showHelpModal} onOpenChange={setShowHelpModal}>
        <DialogContent className="max-w-2xl">
          <div className="p-6">
            <h3 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <HelpCircle className="h-6 w-6 text-blue-600" />
              Help & Support
            </h3>
            <p className="text-gray-600 mb-6">
              Get help with using {tenant.name}'s Bible Quiz platform.
            </p>
            
            <div className="grid md:grid-cols-2 gap-4 mb-6">
              <Card className="p-4 cursor-pointer hover:border-blue-500 transition-colors" onClick={() => handleCTAClick()}>
                <div className="flex items-start gap-3">
                  <BookOpen className="h-8 w-8 text-blue-600 mt-1" />
                  <div>
                    <h4 className="font-semibold mb-1">Getting Started Guide</h4>
                    <p className="text-sm text-gray-600">Learn how to participate in tournaments and practice quizzes</p>
                  </div>
                </div>
              </Card>
              
              <Card className="p-4 cursor-pointer hover:border-blue-500 transition-colors" onClick={() => handleCTAClick()}>
                <div className="flex items-start gap-3">
                  <LifeBuoy className="h-8 w-8 text-green-600 mt-1" />
                  <div>
                    <h4 className="font-semibold mb-1">Contact Support</h4>
                    <p className="text-sm text-gray-600">Create a support ticket for technical assistance</p>
                  </div>
                </div>
              </Card>
              
              <Card className="p-4 cursor-pointer hover:border-blue-500 transition-colors" onClick={() => handleCTAClick()}>
                <div className="flex items-start gap-3">
                  <Users className="h-8 w-8 text-purple-600 mt-1" />
                  <div>
                    <h4 className="font-semibold mb-1">FAQs</h4>
                    <p className="text-sm text-gray-600">Find answers to commonly asked questions</p>
                  </div>
                </div>
              </Card>
              
              <Card className="p-4 cursor-pointer hover:border-blue-500 transition-colors" onClick={() => handleCTAClick()}>
                <div className="flex items-start gap-3">
                  <Trophy className="h-8 w-8 text-yellow-600 mt-1" />
                  <div>
                    <h4 className="font-semibold mb-1">Tournament Rules</h4>
                    <p className="text-sm text-gray-600">Understand tournament formats and scoring</p>
                  </div>
                </div>
              </Card>
            </div>
            
            <div className="text-center text-sm text-gray-500">
              Sign in to access full help resources and contact support
            </div>
          </div>
        </DialogContent>
      </Dialog>

      {/* Auth Modal */}
      <Dialog open={showAuthModal} onOpenChange={setShowAuthModal}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto p-0">
          <AuthSystem 
            onAuthSuccess={() => {
              setShowAuthModal(false);
              onAuthSuccess();
            }}
          />
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default TenantLandingPage;
