import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { 
  Save, 
  Eye, 
  RefreshCw, 
  AlertCircle,
  CheckCircle,
  Globe,
  Users,
  Trophy,
  BookOpen,
  Star
} from 'lucide-react';
import { User, Tenant, storage, STORAGE_KEYS } from '@/lib/mockData';
import { hasPermission } from '@/lib/mockData';
import { useLandingPageContent, createLandingPageContent, activateLandingPageContent } from '@/hooks/useLandingPageContent';

interface TenantLandingContent {
  hero: {
    headline: string;
    subheadline: string;
    ctaText: string;
    ctaSecondaryText: string;
  };
  stats: {
    questionsCount: string;
    activeTournaments: string;
    practiceAccess: string;
  };
  features: Array<{
    id: string;
    icon: string;
    title: string;
    description: string;
    enabled: boolean;
  }>;
  testimonials: Array<{
    id: string;
    name: string;
    role: string;
    content: string;
    rating: number;
    enabled: boolean;
  }>;
  branding: {
    showOrgLogo: boolean;
    showPoweredBy: boolean;
    customFooterText?: string;
  };
  metadata: {
    lastUpdated: string;
    updatedBy: string;
  };
}

interface TenantLandingSettingsProps {
  user: User;
  tenant: Tenant;
}

const defaultContent: TenantLandingContent = {
  hero: {
    headline: 'Join Our Bible Quiz Community',
    subheadline: 'Test your knowledge, compete with others, and grow in your faith.',
    ctaText: 'Get Started',
    ctaSecondaryText: 'I Already Have an Account'
  },
  stats: {
    questionsCount: '5,000+',
    activeTournaments: '1',
    practiceAccess: '24/7'
  },
  features: [
    {
      id: 'tournaments',
      icon: 'trophy',
      title: 'Competitive Tournaments',
      description: 'Join live tournaments and compete with fellow Bible scholars',
      enabled: true
    },
    {
      id: 'practice',
      icon: 'book-open',
      title: 'Practice Mode',
      description: 'Sharpen your skills with unlimited practice questions',
      enabled: true
    },
    {
      id: 'leaderboard',
      icon: 'users',
      title: 'Global Leaderboard',
      description: 'Track your progress and see how you rank',
      enabled: true
    },
    {
      id: 'ai-powered',
      icon: 'star',
      title: 'AI-Powered Questions',
      description: 'Challenging questions generated by advanced AI',
      enabled: true
    }
  ],
  testimonials: [],
  branding: {
    showOrgLogo: true,
    showPoweredBy: true,
    customFooterText: ''
  },
  metadata: {
    lastUpdated: new Date().toISOString(),
    updatedBy: 'system'
  }
};

export default function TenantLandingSettings({ user, tenant }: TenantLandingSettingsProps) {
  // Permission check
  if (!hasPermission(user, 'settings.manage')) {
    return (
      <Card>
        <CardContent className="p-6">
          <div className="flex items-center gap-3 text-amber-600">
            <AlertCircle className="h-5 w-5" />
            <p>You don't have permission to manage landing page settings.</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  // ✅ NEW: Use Landing Page CMS API instead of localStorage
  // See: ARCHITECTURE_DECISION_RECORD_LANDING_PAGE_CMS.md
  const { content: apiContent, loading, error, refetch } = useLandingPageContent(tenant.id);
  
  // Working copy for editing (merged with defaults)
  const [content, setContent] = useState<TenantLandingContent>({
    hero: (apiContent.HERO?.content as TenantLandingContent['hero']) || {
      ...defaultContent.hero,
      headline: `Join ${tenant.name}'s Bible Quiz Community`
    },
    stats: (apiContent.STATS?.content as TenantLandingContent['stats']) || defaultContent.stats,
    features: (apiContent.FEATURES?.content as TenantLandingContent['features']) || defaultContent.features,
    testimonials: (apiContent.TESTIMONIALS?.content as TenantLandingContent['testimonials']) || defaultContent.testimonials,
    branding: (apiContent.BRANDING?.content as TenantLandingContent['branding']) || defaultContent.branding,
    metadata: {
      lastUpdated: new Date().toISOString(),
      updatedBy: user.name
    }
  });
  
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const [previewUrl, setPreviewUrl] = useState('');

  // Update content when API data changes
  useEffect(() => {
    if (!loading && !error) {
      setContent({
        hero: (apiContent.HERO?.content as TenantLandingContent['hero']) || {
          ...defaultContent.hero,
          headline: `Join ${tenant.name}'s Bible Quiz Community`
        },
        stats: (apiContent.STATS?.content as TenantLandingContent['stats']) || defaultContent.stats,
        features: (apiContent.FEATURES?.content as TenantLandingContent['features']) || defaultContent.features,
        testimonials: (apiContent.TESTIMONIALS?.content as TenantLandingContent['testimonials']) || defaultContent.testimonials,
        branding: (apiContent.BRANDING?.content as TenantLandingContent['branding']) || defaultContent.branding,
        metadata: {
          lastUpdated: new Date().toISOString(),
          updatedBy: user.name
        }
      });
    }
    setPreviewUrl(`${window.location.origin}/landing`);
  }, [apiContent, loading, error, tenant.id, tenant.name, user.name]);

  const handleSave = async () => {
    // ✅ NEW: Use Landing Page CMS API with version control
    // See: ARCHITECTURE_DECISION_RECORD_LANDING_PAGE_CMS.md
    try {
      setSaving(true);
      setMessage(null);

      // Create new versions for each section
      const sections = [
        { section: 'HERO', content: content.hero },
        { section: 'STATS', content: content.stats },
        { section: 'FEATURES', content: content.features },
        { section: 'TESTIMONIALS', content: content.testimonials },
        { section: 'BRANDING', content: content.branding }
      ];

      // Create all content versions
      const createdIds: string[] = [];
      for (const { section, content: sectionContent } of sections) {
        const response = await createLandingPageContent(
          tenant.id,
          section,
          sectionContent,
          user.id
        );
        createdIds.push(response.id);
      }

      // Activate all new versions (publish)
      for (const id of createdIds) {
        await activateLandingPageContent(tenant.id, id);
      }

      // Refresh data from API
      await refetch();

      showMessage('success', 'Landing page content published successfully!');
    } catch (error) {
      console.error('Failed to save landing page:', error);
      showMessage('error', `Failed to save landing page content: ${error instanceof Error ? error.message : 'Unknown error'}`);
    } finally {
      setSaving(false);
    }
  };

  const handleReset = () => {
    if (confirm('Reset to default content? This cannot be undone.')) {
      setContent({
        ...defaultContent,
        hero: {
          ...defaultContent.hero,
          headline: `Join ${tenant.name}'s Bible Quiz Community`
        }
      });
      showMessage('success', 'Content reset to defaults');
    }
  };

  const showMessage = (type: 'success' | 'error', text: string) => {
    setMessage({ type, text });
    setTimeout(() => setMessage(null), 5000);
  };

  const updateHero = (field: keyof TenantLandingContent['hero'], value: string) => {
    setContent({
      ...content,
      hero: { ...content.hero, [field]: value }
    });
  };

  const updateStats = (field: keyof TenantLandingContent['stats'], value: string) => {
    setContent({
      ...content,
      stats: { ...content.stats, [field]: value }
    });
  };

  const updateFeature = (id: string, field: string, value: any) => {
    setContent({
      ...content,
      features: content.features.map(f => 
        f.id === id ? { ...f, [field]: value } : f
      )
    });
  };

  const updateBranding = (field: keyof TenantLandingContent['branding'], value: any) => {
    setContent({
      ...content,
      branding: { ...content.branding, [field]: value }
    });
  };

  if (loading) {
    return (
      <Card>
        <CardContent className="p-8 text-center">
          <RefreshCw className="h-8 w-8 animate-spin mx-auto mb-3 text-gray-400" />
          <p className="text-gray-500">Loading landing page settings...</p>
        </CardContent>
      </Card>
    );
  }

  if (error) {
    return (
      <Card>
        <CardContent className="p-8">
          <div className="text-center space-y-4">
            <AlertCircle className="h-12 w-12 mx-auto text-red-500" />
            <div>
              <h3 className="text-lg font-semibold text-red-800 mb-2">Failed to Load Settings</h3>
              <p className="text-gray-600 mb-4">{error.message}</p>
              <Button onClick={() => refetch()} variant="outline">
                <RefreshCw className="h-4 w-4 mr-2" />
                Retry
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold mb-2">Landing Page Settings</h1>
        <p className="text-gray-600">
          Customize your organization's landing page at <strong>{tenant.subdomain}.smartequiz.com</strong>
        </p>
        <p className="text-sm text-gray-500 mt-1">
          This page is shown to visitors before they log in
        </p>
      </div>

      {/* Messages */}
      {message && (
        <Card className={message.type === 'success' ? 'border-green-500 bg-green-50' : 'border-red-500 bg-red-50'}>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              {message.type === 'success' ? (
                <CheckCircle className="h-5 w-5 text-green-600" />
              ) : (
                <AlertCircle className="h-5 w-5 text-red-600" />
              )}
              <p className={message.type === 'success' ? 'text-green-800' : 'text-red-800'}>
                {message.text}
              </p>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Action Buttons */}
      <div className="flex justify-between items-center">
        <div className="flex gap-3">
          <Button onClick={handleSave} disabled={saving}>
            <Save className="h-4 w-4 mr-2" />
            {saving ? 'Saving...' : 'Save Changes'}
          </Button>
          <Button variant="outline" onClick={handleReset}>
            <RefreshCw className="h-4 w-4 mr-2" />
            Reset to Defaults
          </Button>
        </div>
        <Button variant="outline" onClick={() => window.open(previewUrl, '_blank')}>
          <Eye className="h-4 w-4 mr-2" />
          Preview Landing Page
        </Button>
      </div>

      {/* Content Tabs */}
      <Tabs defaultValue="hero" className="space-y-4">
        <TabsList>
          <TabsTrigger value="hero">Hero Section</TabsTrigger>
          <TabsTrigger value="stats">Quick Stats</TabsTrigger>
          <TabsTrigger value="features">Features</TabsTrigger>
          <TabsTrigger value="branding">Branding</TabsTrigger>
        </TabsList>

        {/* Hero Section Tab */}
        <TabsContent value="hero" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Globe className="h-5 w-5" />
                Hero Section
              </CardTitle>
              <CardDescription>
                The main headline and call-to-action that visitors see first
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <Label htmlFor="headline">Headline</Label>
                <Input
                  id="headline"
                  value={content.hero.headline}
                  onChange={(e) => updateHero('headline', e.target.value)}
                  placeholder="Join Our Bible Quiz Community"
                  className="mt-1"
                />
                <p className="text-sm text-gray-500 mt-1">Main headline shown at the top</p>
              </div>

              <div>
                <Label htmlFor="subheadline">Subheadline</Label>
                <Textarea
                  id="subheadline"
                  value={content.hero.subheadline}
                  onChange={(e) => updateHero('subheadline', e.target.value)}
                  placeholder="Test your knowledge, compete with others..."
                  rows={3}
                  className="mt-1"
                />
                <p className="text-sm text-gray-500 mt-1">Supporting text below the headline</p>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="ctaText">Primary Button Text</Label>
                  <Input
                    id="ctaText"
                    value={content.hero.ctaText}
                    onChange={(e) => updateHero('ctaText', e.target.value)}
                    placeholder="Get Started"
                    className="mt-1"
                  />
                </div>

                <div>
                  <Label htmlFor="ctaSecondaryText">Secondary Button Text</Label>
                  <Input
                    id="ctaSecondaryText"
                    value={content.hero.ctaSecondaryText}
                    onChange={(e) => updateHero('ctaSecondaryText', e.target.value)}
                    placeholder="I Already Have an Account"
                    className="mt-1"
                  />
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Quick Stats Tab */}
        <TabsContent value="stats" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Quick Statistics</CardTitle>
              <CardDescription>
                Showcase key metrics to visitors (displayed below hero section)
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <Label htmlFor="questionsCount">Questions Available</Label>
                <Input
                  id="questionsCount"
                  value={content.stats.questionsCount}
                  onChange={(e) => updateStats('questionsCount', e.target.value)}
                  placeholder="5,000+"
                  className="mt-1"
                />
              </div>

              <div>
                <Label htmlFor="activeTournaments">Active Tournaments</Label>
                <Input
                  id="activeTournaments"
                  value={content.stats.activeTournaments}
                  onChange={(e) => updateStats('activeTournaments', e.target.value)}
                  placeholder="1"
                  className="mt-1"
                />
              </div>

              <div>
                <Label htmlFor="practiceAccess">Practice Access</Label>
                <Input
                  id="practiceAccess"
                  value={content.stats.practiceAccess}
                  onChange={(e) => updateStats('practiceAccess', e.target.value)}
                  placeholder="24/7"
                  className="mt-1"
                />
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Features Tab */}
        <TabsContent value="features" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Star className="h-5 w-5" />
                Feature Highlights
              </CardTitle>
              <CardDescription>
                Showcase key features of your quiz platform
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {content.features.map((feature) => (
                <Card key={feature.id} className="border-2">
                  <CardContent className="p-4">
                    <div className="flex items-start justify-between mb-3">
                      <div className="flex items-center gap-2">
                        <Badge variant="outline">{feature.icon}</Badge>
                        <span className="font-semibold">{feature.title}</span>
                      </div>
                      <Switch
                        checked={feature.enabled}
                        onCheckedChange={(checked) => updateFeature(feature.id, 'enabled', checked)}
                      />
                    </div>
                    <div className="space-y-2">
                      <Input
                        value={feature.title}
                        onChange={(e) => updateFeature(feature.id, 'title', e.target.value)}
                        placeholder="Feature title"
                      />
                      <Textarea
                        value={feature.description}
                        onChange={(e) => updateFeature(feature.id, 'description', e.target.value)}
                        placeholder="Feature description"
                        rows={2}
                      />
                    </div>
                  </CardContent>
                </Card>
              ))}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Branding Tab */}
        <TabsContent value="branding" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Branding Options</CardTitle>
              <CardDescription>
                Control white-label and branding settings
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <Label htmlFor="showOrgLogo">Show Organization Logo</Label>
                  <p className="text-sm text-gray-500">Display your logo in the header</p>
                </div>
                <Switch
                  id="showOrgLogo"
                  checked={content.branding.showOrgLogo}
                  onCheckedChange={(checked) => updateBranding('showOrgLogo', checked)}
                />
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <Label htmlFor="showPoweredBy">Show "Powered by Smart eQuiz"</Label>
                  <p className="text-sm text-gray-500">Display platform branding in footer</p>
                </div>
                <Switch
                  id="showPoweredBy"
                  checked={content.branding.showPoweredBy}
                  onCheckedChange={(checked) => updateBranding('showPoweredBy', checked)}
                />
              </div>

              <div>
                <Label htmlFor="customFooterText">Custom Footer Text</Label>
                <Textarea
                  id="customFooterText"
                  value={content.branding.customFooterText || ''}
                  onChange={(e) => updateBranding('customFooterText', e.target.value)}
                  placeholder="Add custom text to the footer (optional)"
                  rows={3}
                  className="mt-1"
                />
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* Metadata */}
      <Card>
        <CardContent className="p-4">
          <div className="text-sm text-gray-500">
            Last updated: {new Date(content.metadata.lastUpdated).toLocaleString()} by {content.metadata.updatedBy}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
